default:  

    - C:\VirtualBox VMs:    M:\Drive\Backup\C\VirtualBox VMs
    - C:\VMware VMs:        M:\Drive\Backup\C\VMware VMs
    - D:\1C:                M:\Drive\Backup\D\1C
    - D:\Apps:              M:\Drive\Backup\D\Apps
    - D:\Аудио:             M:\Drive\Backup\D\Аудио
